on: push
name: Continuous Integration
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    strategy:
      matrix:
        otp: [24.3.4.10, 25.3]
        elixir: [1.13.4, 1.14.4]

    steps:
      - uses: actions/checkout@v4

      - name: Cache dialyzer plts
        uses: actions/cache@v3.3.1
        with:
          path: priv/plts
          key: ${{runner.os}}-${{matrix.otp}}-${{matrix.elixir}}-plts

      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Deps get
        run: mix deps.get
      - name: Check Credo
        run: mix credo
      - name: Check Formatting
        run: mix format --check-formatted
      - name: Run Tests
        run: mix do compile --warnings-as-errors, test
      - name: Dialyzer
        run: mix dialyzer
